spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./data/client
    type: com.zaxxer.hikari.HikariDataSource
    username: sa
    password: password
  output:
    ansi:
      enabled: "ALWAYS"
  main:
    banner-mode: "off"
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    locations: "classpath:db/migration"
    enabled: false

logging:
  level:
    "[com.seek]": DEBUG
    root: INFO
    org.springframework.cache: TRACE

api:
  seek:
    customer:
      edadesMortalidadPeru:
        - 56
        - 89
        - 70
        - 35
        - 67
        - 59
