spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/seek
    username: root
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  output:
    ansi:
      enabled: "ALWAYS"
  main:
    banner-mode: "off"
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    locations: "classpath:db/migration"
    enabled: true

logging:
  level:
    "[com.seek]": DEBUG
    root: INFO
    org.springframework.cache: TRACE


api:
  seek:
    customer:
      edadesMortalidadPeru:
        - 56
        - 89
        - 70
        - 35
        - 67
        - 59
